import { spawn } from "child_process";
import { access, mkdtemp, readFile, readdir, rm, writeFile } from "fs/promises";
import { tmpdir } from "os";
import { basename, join } from "path";

import { NextResponse } from "next/server";

import { PLATFORM_PRESETS } from "@/lib/ffmpeg";
import { createId } from "@/lib/utils";
import { ClipCandidate, Platform, TranscriptSegment, VideoAsset } from "@/types";

export const runtime = "nodejs";

type PreviewRequestPayload = {
  clip: Partial<ClipCandidate> & {
    transcript?: Array<{ id?: string; startMs?: number; endMs?: number; startSec?: number; endSec?: number; text?: string }>;
  };
  asset?: VideoAsset;
  platform?: Platform;
};

type ParsedDataUri = {
  buffer: Buffer;
  extension: string;
};

type PreviewRenderMode = "source" | "poster" | "solid";

function sanitizeBaseName(value: string) {
  const sanitized = value.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "");
  return sanitized || "clipforge_preview";
}

function toMilliseconds(value: number | undefined, fallback: number) {
  if (typeof value !== "number" || Number.isNaN(value)) {
    return fallback;
  }

  return value > 1000 ? value : Math.round(value * 1000);
}

function normalizeTranscript(
  transcript: Array<{ id?: string; startMs?: number; endMs?: number; startSec?: number; endSec?: number; text?: string }> | undefined
) {
  if (!Array.isArray(transcript)) {
    return [];
  }

  return transcript
    .map((segment, index) => {
      const startMs = toMilliseconds(segment.startMs, toMilliseconds(segment.startSec, index * 1000));
      const endMs = toMilliseconds(segment.endMs, toMilliseconds(segment.endSec, startMs + 1200));

      return {
        id: segment.id ?? createId("segment"),
        startMs,
        endMs: Math.max(endMs, startMs + 400),
        text: segment.text?.trim() ?? "",
        confidence: 0.96,
        words: []
      } satisfies TranscriptSegment;
    })
    .filter((segment) => segment.text.length > 0);
}

function normalizeClip(input: PreviewRequestPayload["clip"]): ClipCandidate {
  const transcript = normalizeTranscript(input.transcript);
  const startSec = input.startSec ?? Math.floor((transcript[0]?.startMs ?? 0) / 1000);
  const inferredEndSec = Math.ceil((transcript[transcript.length - 1]?.endMs ?? (startSec + 2) * 1000) / 1000);
  const endSec = input.endSec ?? Math.max(startSec + 1, inferredEndSec);

  return {
    id: input.id ?? createId("clip"),
    projectId: input.projectId ?? createId("project"),
    title: input.title ?? "clipforge preview",
    description: input.description ?? "Vertical short preview generated by ClipForge AI.",
    startSec,
    endSec,
    durationSec: input.durationSec ?? Math.max(1, endSec - startSec),
    viralScore: input.viralScore ?? 82,
    breakdown: input.breakdown ?? {
      hook: 84,
      emotion: 76,
      value: 81,
      narrative: 74,
      quotability: 79,
      platformFit: 86,
      trendAlignment: 72,
      engagementPrediction: 80
    },
    whyItWorks: input.whyItWorks ?? ["Short preview generated from the clip window."],
    hookLine: input.hookLine ?? input.title ?? "ClipForge preview",
    transcript,
    platforms: input.platforms?.length ? input.platforms : ["youtube", "tiktok", "instagram"],
    contentType: input.contentType ?? "education",
    sentiment: input.sentiment ?? "positive",
    status: input.status ?? "approved",
    previewImage:
      input.previewImage ??
      "data:image/svg+xml;utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1080' height='1920'%3E%3Crect width='1080' height='1920' fill='%230b1020'/%3E%3Ctext x='84' y='1580' fill='white' font-size='72' font-family='Arial'%3EClip Preview%3C/text%3E%3C/svg%3E"
  };
}

function parseDataUri(value: string | undefined): ParsedDataUri | null {
  if (!value?.startsWith("data:")) {
    return null;
  }

  const match = value.match(/^data:([^;,]+)(;base64)?,(.*)$/s);
  if (!match) {
    return null;
  }

  const [, mime, base64Flag, rawPayload] = match;
  const extension = mime.split("/")[1]?.replace("svg+xml", "svg") ?? "bin";
  const buffer = base64Flag ? Buffer.from(rawPayload, "base64") : Buffer.from(decodeURIComponent(rawPayload), "utf8");

  return { buffer, extension };
}

async function writeDataUriToTempFile(dataUri: string | undefined, tempDir: string, name: string) {
  const parsed = parseDataUri(dataUri);
  if (!parsed) {
    return null;
  }

  const filePath = join(tempDir, `${name}.${parsed.extension}`);
  await writeFile(filePath, parsed.buffer);
  return filePath;
}

async function runFfmpeg(args: string[]) {
  await new Promise<void>((resolve, reject) => {
    const child = spawn("ffmpeg", args, { stdio: ["ignore", "ignore", "pipe"] });
    let stderr = "";

    child.stderr.on("data", (chunk) => {
      stderr += chunk.toString();
    });

    child.on("error", reject);
    child.on("close", (code) => {
      if (code === 0) {
        resolve();
        return;
      }

      reject(new Error(stderr || `ffmpeg exited with code ${code}`));
    });
  });
}

async function fileExists(filePath: string | undefined) {
  if (!filePath) {
    return false;
  }

  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function resolveStoredAssetPath(asset?: VideoAsset) {
  if (await fileExists(asset?.path)) {
    return asset?.path;
  }

  if (!asset?.name) {
    return null;
  }

  const storageDir = join(process.cwd(), "storage", "uploads");
  try {
    const entries = await readdir(storageDir);
    const safeName = asset.name.replace(/[^a-zA-Z0-9._-]+/g, "_");
    const matched = entries.find((entry) => entry.endsWith(`-${safeName}`) || entry.includes(safeName));
    return matched ? join(storageDir, matched) : null;
  } catch {
    return null;
  }
}

async function createSolidVideo(outputPath: string, width: number, height: number, fps: number, durationSec: number) {
  await runFfmpeg([
    "-y",
    "-f",
    "lavfi",
    "-i",
    `color=c=#0b1020:s=${width}x${height}:d=${durationSec}:r=${fps}`,
    "-f",
    "lavfi",
    "-i",
    "anullsrc=channel_layout=stereo:sample_rate=48000",
    "-shortest",
    "-c:v",
    "libx264",
    "-preset",
    "ultrafast",
    "-pix_fmt",
    "yuv420p",
    "-c:a",
    "aac",
    "-b:a",
    "128k",
    "-movflags",
    "+faststart",
    outputPath
  ]);
}

async function renderPreviewArtifact(
  outputPath: string,
  clip: ClipCandidate,
  asset: VideoAsset | undefined,
  previewImagePath: string | null,
  platform: Platform
): Promise<PreviewRenderMode> {
  const preset = PLATFORM_PRESETS[platform];
  const durationSec = Math.max(1, Math.min(clip.durationSec, preset.maxDurationSec));
  const scaleFilter = `scale=${preset.width}:${preset.height}:force_original_aspect_ratio=increase,crop=${preset.width}:${preset.height},fps=${preset.fps}`;
  const sourcePath = await resolveStoredAssetPath(asset);

  if (sourcePath) {
    try {
      await runFfmpeg([
        "-y",
        "-ss",
        clip.startSec.toFixed(2),
        "-i",
        sourcePath,
        "-t",
        durationSec.toFixed(2),
        "-vf",
        scaleFilter,
        "-map",
        "0:v:0?",
        "-map",
        "0:a:0?",
        "-c:v",
        "libx264",
        "-preset",
        "ultrafast",
        "-pix_fmt",
        "yuv420p",
        "-c:a",
        "aac",
        "-b:a",
        "128k",
        "-ar",
        "48000",
        "-movflags",
        "+faststart",
        outputPath
      ]);
      return "source";
    } catch {
      // Continue to preview-image fallback.
    }
  }

  if (previewImagePath) {
    try {
      const animatedPosterFilter = [
        `scale=${Math.round(preset.width * 1.14)}:${Math.round(preset.height * 1.14)}`,
        `crop=${preset.width}:${preset.height}:(in_w-out_w)/2+sin(n/24)*26:(in_h-out_h)/2+cos(n/30)*34`,
        `fps=${preset.fps}`
      ].join(",");

      await runFfmpeg([
        "-y",
        "-loop",
        "1",
        "-i",
        previewImagePath,
        "-f",
        "lavfi",
        "-i",
        "anullsrc=channel_layout=stereo:sample_rate=48000",
        "-t",
        durationSec.toFixed(2),
        "-vf",
        animatedPosterFilter,
        "-shortest",
        "-c:v",
        "libx264",
        "-preset",
        "ultrafast",
        "-pix_fmt",
        "yuv420p",
        "-c:a",
        "aac",
        "-b:a",
        "128k",
        "-movflags",
        "+faststart",
        outputPath
      ]);
      return "poster";
    } catch {
      // Continue to solid fallback.
    }
  }

  await createSolidVideo(outputPath, preset.width, preset.height, preset.fps, durationSec);
  return "solid";
}

export async function POST(request: Request) {
  const body = (await request.json().catch(() => ({}))) as PreviewRequestPayload;
  const clip = normalizeClip(body.clip ?? {});
  const platform = body.platform ?? (clip.platforms.includes("youtube") ? "youtube" : clip.platforms[0] ?? "tiktok");
  const tempDir = await mkdtemp(join(tmpdir(), "clipforge-preview-"));

  try {
    const baseName = sanitizeBaseName(`${clip.title}-${platform}`);
    const outputPath = join(tempDir, `${baseName}.mp4`);
    const previewImagePath = await writeDataUriToTempFile(clip.previewImage, tempDir, `${baseName}-preview`);

    const renderMode = await renderPreviewArtifact(outputPath, clip, body.asset, previewImagePath, platform);

    const buffer = await readFile(outputPath);
    return new NextResponse(buffer, {
      headers: {
        "Content-Type": "video/mp4",
        "Content-Disposition": `inline; filename="${basename(outputPath)}"`,
        "Cache-Control": "no-store",
        "X-ClipForge-Preview-Platform": platform,
        "X-ClipForge-Preview-Mode": renderMode
      }
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Preview render failed.";
    return NextResponse.json({ error: message }, { status: 500 });
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
}
