import { spawn } from "child_process";
import { access, mkdtemp, readFile, readdir, rm, writeFile } from "fs/promises";
import { tmpdir } from "os";
import { basename, join } from "path";

import JSZip from "jszip";
import { NextResponse } from "next/server";

import { buildExportArtifacts } from "@/modules/clipper/ClipGenerator";
import { generateMetadataBundle } from "@/modules/metadata/MetadataEngine";
import { PLATFORM_PRESETS } from "@/lib/ffmpeg";
import { createId } from "@/lib/utils";
import { CaptionCue, CaptionStyleId, ClipCandidate, MetadataBundle, ThumbnailVariant, VideoAsset } from "@/types";

type ExportRequestPayload = {
  clip: Partial<ClipCandidate> & {
    transcript?: Array<{ id?: string; startMs?: number; endMs?: number; startSec?: number; endSec?: number; text?: string }>;
  };
  metadata?: MetadataBundle;
  asset?: VideoAsset;
  thumbnails?: ThumbnailVariant[];
  cues?: Array<Partial<CaptionCue> & { startSec?: number; endSec?: number }>;
  captionStyle?: CaptionStyleId;
};

type ParsedDataUri = {
  buffer: Buffer;
  extension: string;
};

function sanitizeBaseName(value: string) {
  const sanitized = value.toLowerCase().replace(/[^a-z0-9]+/g, "_").replace(/^_+|_+$/g, "");
  return sanitized || "clipforge_export";
}

function toMilliseconds(value: number | undefined, fallback: number) {
  if (typeof value !== "number" || Number.isNaN(value)) {
    return fallback;
  }

  return value > 1000 ? value : Math.round(value * 1000);
}

function normalizeTranscript(
  transcript: Array<{ id?: string; startMs?: number; endMs?: number; startSec?: number; endSec?: number; text?: string }> | undefined
) {
  if (!Array.isArray(transcript)) {
    return [];
  }

  return transcript
    .map((segment, index) => {
      const startMs = toMilliseconds(segment.startMs, toMilliseconds(segment.startSec, index * 1000));
      const endMs = toMilliseconds(segment.endMs, toMilliseconds(segment.endSec, startMs + 1200));

      return {
        id: segment.id ?? createId("segment"),
        startMs,
        endMs: Math.max(endMs, startMs + 400),
        text: segment.text?.trim() ?? "",
        confidence: 0.96,
        words: []
      };
    })
    .filter((segment) => segment.text.length > 0);
}

function normalizeCuePayload(cues: ExportRequestPayload["cues"]) {
  if (!Array.isArray(cues)) {
    return undefined;
  }

  return cues
    .map((cue, index) => {
      const startMs = toMilliseconds(cue.startMs, toMilliseconds(cue.startSec, index * 1000));
      const endMs = toMilliseconds(cue.endMs, toMilliseconds(cue.endSec, startMs + 1200));

      return {
        id: cue.id ?? createId("cue"),
        startMs,
        endMs: Math.max(endMs, startMs + 400),
        text: cue.text?.trim() ?? "",
        activeWordIndex: cue.activeWordIndex,
        emojis: cue.emojis
      } satisfies CaptionCue;
    })
    .filter((cue) => cue.text.length > 0);
}

function normalizeClip(input: ExportRequestPayload["clip"]): ClipCandidate {
  const transcript = normalizeTranscript(input.transcript);
  const startSec = input.startSec ?? Math.floor((transcript[0]?.startMs ?? 0) / 1000);
  const inferredEndSec = Math.ceil((transcript[transcript.length - 1]?.endMs ?? (startSec + 2) * 1000) / 1000);
  const endSec = input.endSec ?? Math.max(startSec + 1, inferredEndSec);

  return {
    id: input.id ?? createId("clip"),
    projectId: input.projectId ?? createId("project"),
    title: input.title ?? "clipforge export",
    description: input.description ?? "Export package generated by ClipForge AI.",
    startSec,
    endSec,
    durationSec: input.durationSec ?? Math.max(1, endSec - startSec),
    viralScore: input.viralScore ?? 82,
    breakdown: input.breakdown ?? {
      hook: 84,
      emotion: 76,
      value: 81,
      narrative: 74,
      quotability: 79,
      platformFit: 86,
      trendAlignment: 72,
      engagementPrediction: 80
    },
    whyItWorks: input.whyItWorks ?? ["Export-ready clip with valid media, captions, and metadata bundle."],
    hookLine: input.hookLine ?? input.title ?? "ClipForge export",
    transcript,
    platforms: input.platforms?.length ? input.platforms : ["tiktok", "instagram", "youtube"],
    contentType: input.contentType ?? "education",
    sentiment: input.sentiment ?? "positive",
    status: input.status ?? "approved",
    previewImage:
      input.previewImage ??
      "data:image/svg+xml;utf8,%3Csvg xmlns='http://www.w3.org/2000/svg' width='1080' height='1920'%3E%3Crect width='1080' height='1920' fill='%230b1020'/%3E%3Ctext x='84' y='1580' fill='white' font-size='72' font-family='Arial'%3EClip Export%3C/text%3E%3C/svg%3E"
  };
}

function formatTimestamp(ms: number, decimalSeparator: "," | ".") {
  const totalMs = Math.max(0, Math.round(ms));
  const hours = Math.floor(totalMs / 3_600_000);
  const minutes = Math.floor((totalMs % 3_600_000) / 60_000);
  const seconds = Math.floor((totalMs % 60_000) / 1_000);
  const millis = totalMs % 1_000;

  return `${String(hours).padStart(2, "0")}:${String(minutes).padStart(2, "0")}:${String(seconds).padStart(2, "0")}${decimalSeparator}${String(millis).padStart(3, "0")}`;
}

function buildTimedTranscript(clip: ClipCandidate) {
  const offsetMs = clip.transcript[0]?.startMs ?? 0;

  return clip.transcript.map((segment) => ({
    ...segment,
    startMs: Math.max(0, segment.startMs - offsetMs),
    endMs: Math.max(0, segment.endMs - offsetMs)
  }));
}

function normalizeCues(clip: ClipCandidate, cues?: CaptionCue[]) {
  const sourceCues = cues?.length
    ? cues
    : buildTimedTranscript(clip).map((segment, index) => ({
        id: `cue_${index + 1}`,
        startMs: segment.startMs,
        endMs: segment.endMs,
        text: segment.text
      }));

  const offsetMs = sourceCues[0]?.startMs ?? 0;

  return sourceCues.map((cue) => ({
    ...cue,
    startMs: Math.max(0, cue.startMs - offsetMs),
    endMs: Math.max(0, cue.endMs - offsetMs)
  }));
}

function buildSrt(clip: ClipCandidate, cues?: CaptionCue[]) {
  return normalizeCues(clip, cues)
    .map((cue, index) => {
      return `${index + 1}\n${formatTimestamp(cue.startMs, ",")} --> ${formatTimestamp(cue.endMs, ",")}\n${cue.text}\n`;
    })
    .join("\n");
}

function buildVtt(clip: ClipCandidate, cues?: CaptionCue[]) {
  return `WEBVTT\n\n${normalizeCues(clip, cues)
    .map((cue) => {
      return `${formatTimestamp(cue.startMs, ".")} --> ${formatTimestamp(cue.endMs, ".")}\n${cue.text}\n`;
    })
    .join("\n")}`;
}

function formatAssTimestamp(ms: number) {
  const totalMs = Math.max(0, Math.round(ms));
  const hours = Math.floor(totalMs / 3_600_000);
  const minutes = Math.floor((totalMs % 3_600_000) / 60_000);
  const seconds = Math.floor((totalMs % 60_000) / 1_000);
  const centiseconds = Math.floor((totalMs % 1_000) / 10);

  return `${hours}:${String(minutes).padStart(2, "0")}:${String(seconds).padStart(2, "0")}.${String(centiseconds).padStart(2, "0")}`;
}

function escapeAssText(value: string) {
  return value
    .replace(/\\/g, "\\\\")
    .replace(/\{/g, "\\{")
    .replace(/\}/g, "\\}")
    .replace(/\r?\n/g, "\\N");
}

function getAssStyle(style: CaptionStyleId | undefined) {
  switch (style) {
    case "bold-fire":
      return {
        fontName: "Arial",
        fontSize: 18,
        primaryColour: "&H00FFFFFF",
        outlineColour: "&H001015D9",
        backColour: "&H00611F05",
        bold: -1,
        italic: 0,
        borderStyle: 3,
        outline: 1,
        shadow: 0,
        alignment: 2,
        marginL: 80,
        marginR: 80,
        marginV: 120
      };
    case "neon-pop":
      return {
        fontName: "Arial",
        fontSize: 18,
        primaryColour: "&H00FFF7E8",
        outlineColour: "&H00D9A106",
        backColour: "&H00693802",
        bold: -1,
        italic: 0,
        borderStyle: 3,
        outline: 1,
        shadow: 0,
        alignment: 2,
        marginL: 84,
        marginR: 84,
        marginV: 128
      };
    case "minimal-clean":
      return {
        fontName: "Arial",
        fontSize: 16,
        primaryColour: "&H00F9FAFB",
        outlineColour: "&H00333A45",
        backColour: "&H00404852",
        bold: 0,
        italic: 0,
        borderStyle: 3,
        outline: 1,
        shadow: 0,
        alignment: 2,
        marginL: 96,
        marginR: 96,
        marginV: 132
      };
    case "tiktok-native":
      return {
        fontName: "Arial",
        fontSize: 18,
        primaryColour: "&H00FFFFFF",
        outlineColour: "&H00000000",
        backColour: "&H00402020",
        bold: -1,
        italic: 0,
        borderStyle: 3,
        outline: 1,
        shadow: 0,
        alignment: 2,
        marginL: 78,
        marginR: 78,
        marginV: 118
      };
    case "cinematic":
      return {
        fontName: "Georgia",
        fontSize: 16,
        primaryColour: "&H00F7F3E8",
        outlineColour: "&H00000000",
        backColour: "&H00342418",
        bold: 0,
        italic: -1,
        borderStyle: 3,
        outline: 1,
        shadow: 0,
        alignment: 2,
        marginL: 100,
        marginR: 100,
        marginV: 140
      };
    default:
      return {
        fontName: "Arial",
        fontSize: 18,
        primaryColour: "&H00FFFFFF",
        outlineColour: "&H007C3AED",
        backColour: "&H00461A74",
        bold: -1,
        italic: 0,
        borderStyle: 3,
        outline: 1,
        shadow: 0,
        alignment: 2,
        marginL: 80,
        marginR: 80,
        marginV: 122
      };
  }
}

function buildAssSubtitles(clip: ClipCandidate, cues: CaptionCue[] | undefined, styleId: CaptionStyleId | undefined) {
  const style = getAssStyle(styleId);
  const dialogue = normalizeCues(clip, cues)
    .map((cue) => `Dialogue: 0,${formatAssTimestamp(cue.startMs)},${formatAssTimestamp(cue.endMs)},ClipForge,,0,0,0,,${escapeAssText(cue.text)}`)
    .join("\n");

  return [
    "[Script Info]",
    "ScriptType: v4.00+",
    "PlayResX: 1080",
    "PlayResY: 1920",
    "ScaledBorderAndShadow: yes",
    "",
    "[V4+ Styles]",
    "Format: Name,Fontname,Fontsize,PrimaryColour,SecondaryColour,OutlineColour,BackColour,Bold,Italic,Underline,StrikeOut,ScaleX,ScaleY,Spacing,Angle,BorderStyle,Outline,Shadow,Alignment,MarginL,MarginR,MarginV,Encoding",
    `Style: ClipForge,${style.fontName},${style.fontSize},${style.primaryColour},&H000000FF,${style.outlineColour},${style.backColour},${style.bold},${style.italic},0,0,100,100,0,0,${style.borderStyle},${style.outline},${style.shadow},${style.alignment},${style.marginL},${style.marginR},${style.marginV},1`,
    "",
    "[Events]",
    "Format: Layer,Start,End,Style,Name,MarginL,MarginR,MarginV,Effect,Text",
    dialogue
  ].join("\n");
}

function escapeFilterPath(filePath: string) {
  return filePath
    .replace(/\\/g, "/")
    .replace(/:/g, "\\:")
    .replace(/'/g, "\\'")
    .replace(/,/g, "\\,")
    .replace(/\[/g, "\\[")
    .replace(/\]/g, "\\]");
}

function parseDataUri(value: string | undefined): ParsedDataUri | null {
  if (!value?.startsWith("data:")) {
    return null;
  }

  const match = value.match(/^data:([^;,]+)(;base64)?,(.*)$/s);
  if (!match) {
    return null;
  }

  const [, mime, base64Flag, rawPayload] = match;
  const extension = mime.split("/")[1]?.replace("svg+xml", "svg") ?? "bin";
  const buffer = base64Flag ? Buffer.from(rawPayload, "base64") : Buffer.from(decodeURIComponent(rawPayload), "utf8");

  return { buffer, extension };
}

async function runFfmpeg(args: string[]) {
  await new Promise<void>((resolve, reject) => {
    const child = spawn("ffmpeg", args, { stdio: ["ignore", "ignore", "pipe"] });
    let stderr = "";

    child.stderr.on("data", (chunk) => {
      stderr += chunk.toString();
    });

    child.on("error", reject);
    child.on("close", (code) => {
      if (code === 0) {
        resolve();
        return;
      }

      reject(new Error(stderr || `ffmpeg exited with code ${code}`));
    });
  });
}

async function fileExists(filePath: string | undefined) {
  if (!filePath) {
    return false;
  }

  try {
    await access(filePath);
    return true;
  } catch {
    return false;
  }
}

async function resolveStoredAssetPath(asset?: VideoAsset) {
  if (await fileExists(asset?.path)) {
    return asset?.path;
  }

  if (!asset?.name) {
    return null;
  }

  const storageDir = join(process.cwd(), "storage", "uploads");
  try {
    const entries = await readdir(storageDir);
    const safeName = asset.name.replace(/[^a-zA-Z0-9._-]+/g, "_");
    const matched = entries.find((entry) => entry.endsWith(`-${safeName}`) || entry.includes(safeName));
    return matched ? join(storageDir, matched) : null;
  } catch {
    return null;
  }
}

async function writeDataUriToTempFile(dataUri: string | undefined, tempDir: string, name: string) {
  const parsed = parseDataUri(dataUri);
  if (!parsed) {
    return null;
  }

  const filePath = join(tempDir, `${name}.${parsed.extension}`);
  await writeFile(filePath, parsed.buffer);
  return filePath;
}

async function createSolidVideo(outputPath: string, width: number, height: number, fps: number, durationSec: number) {
  await runFfmpeg([
    "-y",
    "-f",
    "lavfi",
    "-i",
    `color=c=#0b1020:s=${width}x${height}:d=${durationSec}:r=${fps}`,
    "-f",
    "lavfi",
    "-i",
    "anullsrc=channel_layout=stereo:sample_rate=48000",
    "-shortest",
    "-c:v",
    "libx264",
    "-preset",
    "ultrafast",
    "-pix_fmt",
    "yuv420p",
    "-c:a",
    "aac",
    "-b:a",
    "128k",
    "-movflags",
    "+faststart",
    outputPath
  ]);
}

async function burnSubtitleTrack(inputPath: string, outputPath: string, subtitlePath: string) {
  await runFfmpeg([
    "-y",
    "-i",
    inputPath,
    "-vf",
    `subtitles='${escapeFilterPath(subtitlePath)}'`,
    "-c:v",
    "libx264",
    "-preset",
    "ultrafast",
    "-pix_fmt",
    "yuv420p",
    "-c:a",
    "copy",
    "-movflags",
    "+faststart",
    outputPath
  ]);
}

async function createSolidImage(outputPath: string, width: number, height: number) {
  await runFfmpeg([
    "-y",
    "-f",
    "lavfi",
    "-i",
    `color=c=#111827:s=${width}x${height}`,
    "-frames:v",
    "1",
    outputPath
  ]);
}

async function renderVideoArtifact(
  outputPath: string,
  clip: ClipCandidate,
  asset: VideoAsset | undefined,
  previewImagePath: string | null,
  platform: keyof typeof PLATFORM_PRESETS,
  subtitlePath: string | null
) {
  const preset = PLATFORM_PRESETS[platform];
  const durationSec = Math.max(1, Math.min(clip.durationSec, preset.maxDurationSec));
  const subtitleFilter = subtitlePath ? `,subtitles='${escapeFilterPath(subtitlePath)}'` : "";
  const scaleFilter = `scale=${preset.width}:${preset.height}:force_original_aspect_ratio=increase,crop=${preset.width}:${preset.height},fps=${preset.fps}${subtitleFilter}`;
  const sourcePath = await resolveStoredAssetPath(asset);

  if (sourcePath) {
    try {
      await runFfmpeg([
        "-y",
        "-ss",
        clip.startSec.toFixed(2),
        "-i",
        sourcePath,
        "-t",
        durationSec.toFixed(2),
        "-vf",
        scaleFilter,
        "-map",
        "0:v:0?",
        "-map",
        "0:a:0?",
        "-c:v",
        "libx264",
        "-preset",
        "ultrafast",
        "-pix_fmt",
        "yuv420p",
        "-c:a",
        "aac",
        "-b:a",
        "128k",
        "-ar",
        "48000",
        "-movflags",
        "+faststart",
        outputPath
      ]);
      return;
    } catch {
      // Fall back to synthetic export below.
    }
  }

  if (previewImagePath) {
    try {
      await runFfmpeg([
        "-y",
        "-loop",
        "1",
        "-i",
        previewImagePath,
        "-f",
        "lavfi",
        "-i",
        "anullsrc=channel_layout=stereo:sample_rate=48000",
        "-t",
        durationSec.toFixed(2),
        "-vf",
        scaleFilter,
        "-shortest",
        "-c:v",
        "libx264",
        "-preset",
        "ultrafast",
        "-pix_fmt",
        "yuv420p",
        "-c:a",
        "aac",
        "-b:a",
        "128k",
        "-movflags",
        "+faststart",
        outputPath
      ]);
      return;
    } catch {
      // Continue to solid fallback.
    }
  }

  if (!subtitlePath) {
    await createSolidVideo(outputPath, preset.width, preset.height, preset.fps, durationSec);
    return;
  }

  const baseVideoPath = `${outputPath}.base.mp4`;
  await createSolidVideo(baseVideoPath, preset.width, preset.height, preset.fps, durationSec);
  await burnSubtitleTrack(baseVideoPath, outputPath, subtitlePath);
}

async function renderThumbnailArtifact(
  outputPath: string,
  clip: ClipCandidate,
  asset: VideoAsset | undefined,
  thumbnailImagePath: string | null,
  size: "1280x720" | "1080x1080"
) {
  const [width, height] = size.split("x");
  const scaleFilter = `scale=${width}:${height}:force_original_aspect_ratio=increase,crop=${width}:${height}`;
  const sourcePath = await resolveStoredAssetPath(asset);

  if (sourcePath) {
    try {
      await runFfmpeg([
        "-y",
        "-ss",
        Math.max(0, clip.startSec + 0.4).toFixed(2),
        "-i",
        sourcePath,
        "-frames:v",
        "1",
        "-vf",
        scaleFilter,
        outputPath
      ]);
      return;
    } catch {
      // Continue to preview/fallback generation.
    }
  }

  if (thumbnailImagePath) {
    try {
      await runFfmpeg([
        "-y",
        "-i",
        thumbnailImagePath,
        "-frames:v",
        "1",
        "-vf",
        scaleFilter,
        outputPath
      ]);
      return;
    } catch {
      // Continue to solid fallback.
    }
  }

  await createSolidImage(outputPath, Number(width), Number(height));
}

export async function POST(request: Request) {
  const body = (await request.json()) as ExportRequestPayload;
  const clip = normalizeClip(body.clip);
  const cues = normalizeCuePayload(body.cues);
  const zip = new JSZip();
  const artifacts = buildExportArtifacts(clip);
  const metadata = body.metadata ?? generateMetadataBundle(clip);
  const tempDir = await mkdtemp(join(tmpdir(), "clipforge-export-"));

  try {
    const baseName = sanitizeBaseName(clip.title);
    const previewImagePath = await writeDataUriToTempFile(clip.previewImage, tempDir, `${baseName}-preview`);
    const thumbnailBySize = new Map((body.thumbnails ?? []).map((item) => [item.size, item.image]));
    const ytThumbnailPath = await writeDataUriToTempFile(thumbnailBySize.get("1280x720"), tempDir, `${baseName}-yt-thumb`);
    const igThumbnailPath = await writeDataUriToTempFile(thumbnailBySize.get("1080x1080"), tempDir, `${baseName}-ig-thumb`);

    for (const artifact of artifacts) {
      if (artifact.name.endsWith(".json")) {
        zip.file(artifact.name, JSON.stringify(metadata, null, 2));
        continue;
      }

      if (artifact.name.endsWith(".srt")) {
        zip.file(artifact.name, buildSrt(clip, cues));
        continue;
      }

      if (artifact.name.endsWith(".vtt")) {
        zip.file(artifact.name, buildVtt(clip, cues));
        continue;
      }

      const outputPath = join(tempDir, basename(artifact.name));

      const hasSubtitleContent = normalizeCues(clip, cues).length > 0;
      const subtitlePath = hasSubtitleContent ? join(tempDir, `${baseName}-${body.captionStyle ?? "creator-pro"}.ass`) : null;

      if (subtitlePath && !(await fileExists(subtitlePath))) {
        await writeFile(subtitlePath, buildAssSubtitles(clip, cues, body.captionStyle), "utf8");
      }

      if (artifact.name.endsWith(".mp4")) {
        const platform = artifact.name.includes("_tiktok.")
          ? "tiktok"
          : artifact.name.includes("_instagram.")
            ? "instagram"
            : artifact.name.includes("_square.")
              ? "square"
            : "youtube";

        await renderVideoArtifact(outputPath, clip, body.asset, previewImagePath, platform, subtitlePath);
        zip.file(artifact.name, await readFile(outputPath));
        continue;
      }

      if (artifact.name.endsWith("_thumbnail_yt.jpg")) {
        await renderThumbnailArtifact(outputPath, clip, body.asset, ytThumbnailPath ?? previewImagePath, "1280x720");
        zip.file(artifact.name, await readFile(outputPath));
        continue;
      }

      if (artifact.name.endsWith("_thumbnail_ig.jpg")) {
        await renderThumbnailArtifact(outputPath, clip, body.asset, igThumbnailPath ?? previewImagePath, "1080x1080");
        zip.file(artifact.name, await readFile(outputPath));
      }
    }

    const buffer = await zip.generateAsync({ type: "uint8array" });
    const zipBuffer = Buffer.from(buffer);

    return new NextResponse(zipBuffer, {
      headers: {
        "Content-Type": "application/zip",
        "Content-Disposition": `attachment; filename="${sanitizeBaseName(clip.id)}.zip"`
      }
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Export failed.";
    return NextResponse.json({ error: message }, { status: 500 });
  } finally {
    await rm(tempDir, { recursive: true, force: true });
  }
}
